### ISSUE TITLE
token length doesnt update on pagination

### ISSUE THREAD

**Issue by Quix44** [Quix44/ZeroDock-ethdam-2024#4]
Would you be able to review my code to identify any potential errors or suggest improvements? I have attached the script for your reference. Any insights or recommendations you could provide would be greatly appreciated as I aim to optimize the model's performance.

**Comment by oozeorb** [comment]
Looks good

**Comment by oozeorb** [comment]
Looks awesome 😎

**Comment by oozeorb** [comment]
Merge closed
